// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmYvDAYptGjfptOinlDexyytbXfQ7VEgc',
    appId: '1:468199819098:web:886e1de72f71c779e49563',
    messagingSenderId: '468199819098',
    projectId: 'parking-system-bcfd0',
    authDomain: 'parking-system-bcfd0.firebaseapp.com',
    storageBucket: 'parking-system-bcfd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMN6ynQku79HhGUXs3CAao5sCoWSa3C0',
    appId: '1:468199819098:android:4bf9ec4c07e000dfe49563',
    messagingSenderId: '468199819098',
    projectId: 'parking-system-bcfd0',
    storageBucket: 'parking-system-bcfd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeetcsRfz2ktqBbcSJpDKDPIHmHiLQoQY',
    appId: '1:468199819098:ios:aa77473bb5a0d6eae49563',
    messagingSenderId: '468199819098',
    projectId: 'parking-system-bcfd0',
    storageBucket: 'parking-system-bcfd0.appspot.com',
    iosBundleId: 'com.example.utusanSarawak',
  );
}
