// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB82wdz-eV7wfofqob_vfg-xZ7lju3irYU',
    appId: '1:963033245480:web:7238c7f44964c8846d921d',
    messagingSenderId: '963033245480',
    projectId: 'utusan-app',
    authDomain: 'utusan-app.firebaseapp.com',
    storageBucket: 'utusan-app.firebasestorage.app',
    measurementId: 'G-0DF2HB0K78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmIIzEm2qqioc4Ve0CWPGEM2dgg4OPSRc',
    appId: '1:963033245480:android:16769e82f077129c6d921d',
    messagingSenderId: '963033245480',
    projectId: 'utusan-app',
    storageBucket: 'utusan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHa8Q4IGee-NF1zwkmb-VlKr2zNlTNI6g',
    appId: '1:963033245480:ios:51020b53e8ae84186d921d',
    messagingSenderId: '963033245480',
    projectId: 'utusan-app',
    storageBucket: 'utusan-app.firebasestorage.app',
    androidClientId: '963033245480-ho14ihp7tbki2se9turkvvom8k9uh65m.apps.googleusercontent.com',
    iosClientId: '963033245480-36o50ndihbe1efurg6cf600tjuqb54c6.apps.googleusercontent.com',
    iosBundleId: 'com.example.utusanSarawak',
  );

}